# base.yaml (纯粹的训练引擎与硬件基座)

training:
  device: "cuda:0"                 # 单卡 4090 直接使用 cuda:0
  batch_size: 4                   # 训练时的 micro-batch size
  gradient_accumulation_steps: 8   # 梯度累积，等效 Global Batch Size = 32
  learning_rate: 2.0e-5
  epochs: 3
  max_grad_norm: 1.0
  # eval_every_n_steps: 24           # 每 24 步评估一次
  eval_batch_size: 2               # [重要] 4090 防 OOM 专用：评估生成时的并发量

  save_every_n_epochs: 3
  save_logs: "output_log/math_sft/sft_logs_Bespoke17k.txt"           # 训练日志保存路径
  temperature: 0.7

  # 核采样概率 
  top_p: 0.95

wandb:
  project_name: "cs336-alignment-sft"