# configs/grpo_base_online(REINFORCE).yaml
model:
  model_path: "train_data/models/Qwen2.5-Math-1.5B"
  dtype: "bfloat16"
  attn_implementation: "flash_attention_2"
  start_step: 0
  wandb_id: null

data:
  train_path: "train_data/datasets/Bespoke17k/validation_rl.jsonl"
  prompt_path: "cs336_alignment/prompts/r1_zero.prompt"
  max_seq_length: 4096
  max_samples: 5000

training:
  output_dir: "output/grpo_final_model"       
  checkpoint_dir: "checkpoints/grpo_steps"    
  n_grpo_steps: 200
  warmup_ratio: 0.1
  learning_rate: 5.0e-6
  advantage_eps: 1.0e-6
  max_grad_norm: 1.0
  save_steps: 50

  rollout_batch_size: 64
  group_size: 8
  micro_batch_size: 3
  epochs_per_rollout_batch: 1
  loss_type: "grpo_clip"
  clip_range: 0.2

  normalize_by_std: True
  remove_length_norm: False
  fixed_norm_length: null
  length_panelty: True

  sampling_temperature: 1.0
  repetition_penalty: 1.0
  sampling_min_tokens: 4
  sampling_max_tokens: 4096
  stop_tokens: ["</answer>", "<|endoftext|>"]

  gradient_checkpointing: True
  enforce_eager: True
  enable_prefix_caching: False
  gpu_memory_utilization: 0.25


validation:
  valid_path: "train_data/datasets/Bespoke17k/validation_rl.jsonl"
  max_samples: 100            
  eval_every_steps: 20



evaluation:
  save_logs: "output_log/grpo_final_eval_logs.txt"

wandb:
  project: "CS336-Assignment5-Alignment——GRPO"
  run_name: "grpo_base_REINFORCE_training"
  entity: null