# 文件名: 04_weight_tying.yaml
project_name: "cs336-exp4-tying"

common:
  data:
    train_path: "data/TinyStories_train.npy"
    val_path: "data/TinyStories_val.npy"
  training:
    device: "cuda"
    batch_size: 64
    max_iters: 20000
    learning_rate: 3e-4
    min_lr: 3e-5
    warmup_iters: 1000
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    eps: 1e-8
    grad_clip: 1.0
  checkpoint:
    out_dir_base: "checkpoints/exp4"
    save_interval: 2000

experiments:
  - run_name: "Weight-Tied"
    model:
      vocab_size: 10000
      context_length: 256
      d_model: 256
      num_layers: 4
      num_heads: 4
      d_ff: 1024
      pos_emb_type: "learned"
      norm_location: "post"
      norm_type: "layernorm"
      ffn_type: "relu"
      weight_tying: true     # <--- 变量
      dropout: 0.1

  - run_name: "Weight-Untied"
    model:
      vocab_size: 10000
      context_length: 256
      d_model: 256
      num_layers: 4
      num_heads: 4
      d_ff: 1024
      pos_emb_type: "learned"
      norm_location: "post"
      norm_type: "layernorm"
      ffn_type: "relu"
      weight_tying: false    # <--- 变量
      dropout: 0.1