# exp_bespoke_128.yaml (具体的实验名片)

model:
  model_id: "train_data/models/Qwen2.5-Math-1.5B"
  output_dir: "output/qwen_sft_bespoke_128_final"
  checkpoint_dir: "checkpoints/qwen_sft_bespoke_128_checkpoints" # [新增] 断点检查点保存路径

data:
  train_path: "train_data/datasets/Bespoke17k/sft.jsonl"
  val_path: "train_data/datasets/Bespoke17k/validation.jsonl"
  num_train_examples: 128
  filter_correct_only: false       # 第一阶段不过滤，照单全收
  num_val_examples: 200            # 每次评估 200 条

wandb:
  run_name: "qwen_sft_bespoke_128"